# Generated by Django 3.2.17 on 2023-05-01 19:37

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_jira', '0002_auto_20210330_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiracredentials',
            name='cred_url',
            field=models.CharField(default='https://www.ebi.ac.uk/panda/jira/', max_length=255, verbose_name='Access Url'),
        ),
        migrations.AlterField(
            model_name='jiracredentials',
            name='credentials',
            field=fernet_fields.fields.EncryptedCharField(help_text='https://www.ebi.ac.uk/panda/jira/secure/ViewProfile.jspa?selectedTab=com.atlassian.pats.pats-plugin:jira-user-personal-access-tokens', max_length=255, verbose_name='Token'),
        ),
    ]
