# Generated by Django 3.1.7 on 2021-03-30 17:22

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_jira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraCredentials',
            fields=[
                ('cred_id', models.AutoField(primary_key=True, serialize=False)),
                ('cred_name', models.CharField(default='Jira', editable=False, max_length=150, unique=True, verbose_name='Name')),
                ('cred_url', models.CharField(max_length=255, verbose_name='Access Url')),
                ('user', models.CharField(max_length=100, verbose_name='User Name')),
                ('credentials', fernet_fields.fields.EncryptedCharField(max_length=255, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Jira Credential',
                'verbose_name_plural': 'Jira Credentials',
            },
        ),
        migrations.DeleteModel(
            name='Intention',
        ),
        migrations.CreateModel(
            name='RRBug',
            fields=[
            ],
            options={
                'verbose_name': 'Rapid Release Bug',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ensembl_jira.jirafakemodel',),
        ),
    ]
