language: python
os: linux
dist: xenial
python:
  - "3.8"
  - "3.7"
services:
  - mysql
env:
  - DJANGO=3.1.7 DB=sqlite DEBUG=f
install:
  - pip install -r requirements-dev.txt
script:
  - coverage run --source='.' ./src/manage.py test
