language: python
os: linux
dist: xenial
python:
  - "3.8"
  - "3.7"
  - "3.9"
services:
  - mysql
env:
  - DB=sqlite DEBUG=f
install:
  - pip install -r requirements-dev.txt
script:
  - coverage run --source='.' ./src/manage.py test
