version: '3.3'
services:
  ensembl_jira:
    build: .
    command: >
      sh -c "python manage.py flush --no-input &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn ensembl_jira.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - 'ensembl_jira:/usr/src/ensembl_jira/'
      - 'static_volume:/usr/src/ensembl_jira/staticfiles'
    expose:
      - 8000
    environment:
      - SECRET_KEY=ThisIsASampleSecretKeyLongEnoughForRun
      - PROD_ENGINE=django.db.backends.mysql
      - PROD_DATABASE=ensembl_production_96
      - PROD_USER=root
      - PROD_PASSWORD=
      - PROD_HOST=127.0.0.1
      - PROD_PORT=3306
      - DATABASE=mysql
      - DEBUG=False
    networks:
      - app_network
    ports:
      - '9000:8000'
  nginx:
    build: bin/nginx
    volumes:
      - 'static_volume:/usr/src/ensembl_jira/staticfiles'
    ports:
      - '1337:80'
    depends_on:
      - ensembl_jira
    networks:
      - app_network
volumes:
  static_volume: null
  app: null
networks:
  app_network:
    driver: bridge